name: CBRN-Critical Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'assets/**'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: read   # 最低权限原则
  pages: write
  id-token: write  # 必要OIDC令牌

concurrency: 
  group: "pages-deploy"
  cancel-in-progress: true

jobs:
  security_audit:
    runs-on: ubuntu-24.04-nuclear  # 使用合规环境
    steps:
      - name: IAEA Security Scan
        uses: iaea-actions/ssr6-compliance-check@v3
        with:
          facility-type: 'mobile_decon_system'
          
      - name: Digital Signature Verification
        uses: military-actions/stanag-4632-integrity@v1.8
        env:
          NATO_SECRET_KEY: ${{ secrets.NATO_SIGNING_KEY }}

  build:
    runs-on: ubuntu-latest
    needs: security_audit
    env:
      NUCLEAR_SAFETY_LEVEL: 3
    steps:
      - name: Checkout with IAEA Safeguards
        uses: actions/checkout@v4
        with:
          repository: 'kapmif/CrisisTech-OSS'
          ref: 'main'
          ssh-key: ${{ secrets.IAEA_SSH_DEPLOY }}
          clean: true
          sparse-checkout: |
            docs/
            assets/
            index.html

      - name: Radiation Dataset Validation
        run: |
          jq -e '.validation_protocols' docs/compliance/radiation.json
          echo "SCALE 6.2.3 checksum: $(sha256sum docs/scale623.dat)"

      - name: Generate Non-Proliferation Manifest
        run: |
          echo "OPCW_CONVENTION_ID=$(date +%Y%m%d)-CTOSS" >> $GITHUB_ENV
          echo "IAEA_INSPECTION_CODE=${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Upload with Dual Authorization
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          nuclear-facility-id: ${{ secrets.IAEA_FACILITY_CODE }}
          retention-days: 7  # 符合记录保留规范

  deploy:
    environment: 
      name: chernobyl_zone
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-nuclear
    needs: build
    steps:
      - name: Deploy under IAEA Oversight
        id: deployment
        uses: iaea-actions/deploy-nuclear-pages@v2
        with:
          target-branch: gh-pages
          safeguard-level: 4
          neutron-shielding: true
          
      - name: Post-Deployment Survey
        uses: military-actions/radiation-survey@v2.1
        with:
          geiger-counter-threshold: 300  # μSv/h
          
      - name: Compliance Webhook
        if: always()
        run: |
          curl -X POST -H "Authorization: Bearer ${{secrets.OPCW_REPORT_KEY}}" \
          https://compliance.opcw.org/deployments \
          -d status=${{ job.status }} \
          -d facility_id=${{ secrets.IAEA_FACILITY_CODE }}
