# .github/workflows/find-repos.yml
name: Repository Monitor

on:
  schedule:
    - cron: '0 12 * * 1' # 每周一中午运行
  workflow_dispatch:

jobs:
  search-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Run Monitor
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        pip install pygithub
        python fetch_repos.py
